// Sidebar for the versioned RPC API instance (pluginId: "api").
const sidebars = {
  apiSidebar: [
    {
      type: "link",
      label: "← Build documentation",
      href: "/docs/build/overview",
    },
    {
      type: "autogenerated",
      dirName: ".",
    },
  ],
};

export default sidebars;
